### ISSUE TITLE
코드리뷰 피드백

### ISSUE THREAD

**Issue by paran22** [Hajin-Bang/Project_BookMark#34]
- 모든 네이밍은 일관성을 유지하는게 좋습니다. 예를 들어 페이지 컴포넌트들 중 어떤 컴포넌트는 **Page로 끝나고, 어떤 컴포넌트는 Page가 붙어있지 않아요. 네이밍을 일관성으로 유지하여 협업 하기도 좋고, 혼자 프로젝트를 하더라도 나중에 코드를 봤을 때 이해하기 쉬워집니다.
- 전체적으로 쿼리키는 잘 구성해주신 것 같아요. 추가로 products나 carts 등 쿼리키는 상수로 관리하는 것이 좋습니다. 의도적으로 동일한 도메인을 동일한 쿼리키로 시작하도록 했을 때, 하드코딩을 하면 오타가 발생할 수도 있고, 변경됬을 때 하나하나 다 찾아서 변경을 해야하기 때문에 이런 값들은 상수로 관리하시는게 좋아요.
- 언급하신 에러(카테고리 페이지에서 상세로 갔다가 뒤로가기했을 때)는 쿼리키 문제는 아닌 것 같구요. 카테고리 페이지와 상세페이지에서 모두 useFetchProducts를 동일하게 사용하고 있다는 점이 조금 걸리네요. Tanstack query devtool로 쿼리 상태들을 체크해보셔야 할 것 같아요. 또, 상세페이지의 경우에는 하나의 product만 조회하기 때문에 굳이 useInfiniteQuery를 사용하는 useFetchProducts를 사용할 필요는 없을 것 같아요. 별도로 제품을 상세 조회하는 api를 만드는 것이 깔끔할 것 같네요.
- authStatusType같은 상수는 as const를 붙여서 변경이 불가능한 상수로 만들어주시면 좋습니다. 네이밍 컨벤션은 프로젝트마다 다를 수 있을텐데 상수라는 걸 고려하면 AUTH_STATUS_TYPE도 괜찮을 것 같네요.
- api에 있는 함수 이름들은 ~~API대신 get/post/put/delete를 사용하는 것도 좋습니다. 지금 이름도 어떤 api인지는 잘 드러나서 괜찮은 것 같구요.

**Comment by Hajin-Bang** [comment]
피드백 주신 내용 반영했습니다 감사합니다🙇‍♀️😀!
