### ISSUE TITLE
4주차 코드리뷰 피드백

### ISSUE THREAD

**Issue by paran22** [Hajin-Bang/Project_BookMark#59]
### 이미지 최적화
- 현재 이미지 최적화 옵션에 maxWidthOrHeight가 800으로 설정이 되어 있는데요. 이 값은 현재 프로젝트 내에서 이미지가 어느정도 사이즈로 사용되는지에 따라 달라질 수 있을 것 같아요. 800 이상으로 큰 사이즈가 없다면 현재 설정도 괜찮을 것 같습니다.
- `uploadImageToFirebase`와 파이어베이스에 이미지를 업로드하고 url을 다운로드 하는 함수이고, `deleteImageFormFirebaes`는 파이어베이스에 있는 이미지 파일을 삭제하는 함수같아요. 네트워크를 통해 db에 접근하고 있기 때문에 해당 부분은 api.ts로 함수를 만드는게 좋을 것 같네요. 
- `ImageUploader`는 현재 상태도 괜찮지만 로직을 ui와 분리하고 싶다면 `useImageUploader`와 같은 훅을 만드는 것도 하나의 방법이 될 수 있어요. 또, 현재 /product 아래에 위치하고 있는데 이미지 업로드 자체는 좀 더 일반적으로 사용할 수 있을 것 같아서 /common 아래에 위치시켜도 좋을 것 같네요.
- /src/components에 auth, cart, order, product와 common과 ui는 동일한 depth로 볼 수 없을 것 같아요. /components/features/auth 와 같이 특정 기능과 관련된 컴포넌트들은 features 폴더로 묶는 것도 괜찮을 것 같아요.

### toast
- Toast 잘 만들어진 것 같아요! 여러 개가 띄워졌을 때도 고려하셨고, toast는 자동으로 꺼지는 경우기 많은데 이 부분도 잘 고려가 되었네요~
- 디자인 시스템에서 조금 아쉬운 점은 현재 테스트를 위해 DesignTestPage가 있다는 점이에요. 개발을 위해서만 사용되는 페이지라서 storybook을 사용하면 조금 더 깔끔할 것 같아요!

**Comment by Hajin-Bang** [comment]
피드백 주신 내용 반영하였습니다! 감사합니다🙇‍♀️🙇‍♀️🙇‍♀️
